### ISSUE TITLE
Compatibility with hiera-eyaml 2.0+

### ISSUE THREAD

**Issue by andrekeller** [sihil/hiera-eyaml-gpg#22]
root@puppet:~# gem install hiera-eyaml-gpg
Building native extensions.  This could take a while...
Fetching: hiera-eyaml-gpg-0.4.gem (100%)
Successfully installed gpgme-2.0.8
Successfully installed hiera-eyaml-gpg-0.4
2 gems installed
Installing ri documentation for gpgme-2.0.8...
Installing ri documentation for hiera-eyaml-gpg-0.4...
Installing RDoc documentation for gpgme-2.0.8...
Installing RDoc documentation for hiera-eyaml-gpg-0.4...

root@puppet:~# eyaml version
[hiera-eyaml-core] hiera-eyaml (core): 2.0.6
[hiera-eyaml-core] hiera-eyaml-gpg (gem): unknown (is plugin compatible with eyaml 2.0+ ?)

The plugin seems to work properly though.

**Comment by andrekeller** [comment]
oops duplicate of #20

**Comment by alexjfisher** [comment]
I don't think this was a duplicate.

The `unknown (is plugin compatible with eyaml 2.0+ ?)` warning is fixed in https://github.com/voxpupuli/hiera-eyaml-gpg/pull/58
